---
title: "Modeling the Effectiveness of California's COVID Response"
author: "Kurt Stoneburner"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

#### Set the working directory, to the active script folder
workingDir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(workingDir)

################################################################################
### Load Models from RDS File.
### R Markdown couldn't handle the whole project, it became very cumbersone
################################################################################
death_model_df          <- readRDS("model_death_model_df.dat")
death_model_last_30_df  <- readRDS("model_death_model_last_30_df")
death_model_post_may_df <- readRDS("model_death_model_post_may_df")



```

## R Markdown

## Plots


```{r plots1, echo=FALSE}
### Model Error Rate Comparison
ggplot() + theme_light() + theme(panel.background = element_rect(fill = "lavenderblush")) +
  geom_line(data = death_model_df, size=1.5 ,aes(y = confirm_death_mse, x = date, color="Confirmed Predict Death") ) +
  geom_line(data = death_model_df, size=1,   aes(y = testing_death_mse, x = date, color="Testing Predict Death" )) +
  geom_line(data = death_model_df, size=.5, aes(y = hospital_death_mse, x = date, color="Hospital Predict Death" ),  ) +
  geom_line(data = death_model_df, size=.5, aes(y = icu_death_mse,      x = date, color="ICU Predict Death" ) ) +
  scale_color_manual(values = c(
  "Confirmed Predict Death" = "darkred",
  "Testing Predict Death" = "#E17876",
  "Hospital Predict Death" = "#2D6A4D",
  "ICU Predict Death" = "#59411A"
  ),name="models") +
  labs( x="Date", 
        y="Relative Model Error (MSE)", 
        name="Models:", 
        title="Relative Model Error Rates", 
        subtitle="Combined County Models (Lower is Better)"  )  

########################################
### MSE
### Confirmed Predicting Deaths 
########################################
ggplot() + theme_light() + 
  theme(
    panel.background = element_rect(fill = "lavenderblush"),
    legend.position = c(.79,.94), 
    legend.direction = "vertical") +
  geom_line(data = death_model_df ,aes(y = confirm_death_mse, x = date, color="Confirmed Cases Predicting Death") ) +
  scale_color_manual(values = c(
    "Confirmed Cases Predicting Death" = "darkred"
  ),name="Model") +
  labs( x="Date", y="Model Error (MSE)", name="", 
        title="Relative California COVID Testing effectiveness", subtitle="Model error as a proxy for effectiveness\n(Lower is Better)"  )  





############################################################
### Last 30 Days
### Confirmed Predicting Deaths vs actual Confirmed/Deaths
############################################################
ggplot() + theme_light() + 
  theme( 
    panel.background = element_rect(fill = "lavenderblush"), 
    legend.position = c(.3,.95), 
    legend.direction = "horizontal") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  geom_line(data = death_model_last_30_df , size=1, aes(y = daily_total_confirmed, x = confirm_death_predict, color="Death Prediction Based on Confirmed Cases") ) +
  geom_point(data = death_model_last_30_df, size=1.5,aes(y = daily_total_confirmed, x = daily_total_deaths),color='blue') +
  scale_color_manual(values = c(
    "Death Prediction Based on Confirmed Cases" = "darkred"
  ),name="") +
  labs( title="California Confirmed Cases vs Deaths", 
        subtitle="With Regression Prediction (Last 30 Days)",
        y="Total California Confirmed Cases",
        x="Total California Covid Deaths" 
  )  



ggplot() + theme_light() + 
  theme( 
    panel.background = element_rect(fill = "lavenderblush"), 
    legend.position = c(.27,.89), 
    legend.direction = "vertical") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  geom_point(data = death_model_last_30_df, size=1.5,aes(y = daily_total_confirmed,   x = daily_total_deaths),color='blue') +
  
  geom_line(data = death_model_last_30_df, size=.5, aes(y = daily_total_confirmed,    x = hospital_death_predict, color="Hospital Predict Death" ),  ) +
  geom_line(data = death_model_last_30_df, size=.5, aes(y = daily_total_confirmed,    x = icu_death_prediction, color="ICU Predict Death" ) ) +
  geom_line(data = death_model_last_30_df , size=1, aes(y = daily_total_confirmed,  x = confirm_death_predict, color="Death Prediction Based on Confirmed Cases") ) +
  geom_line(data = death_model_last_30_df, size=1,   aes(y = daily_total_confirmed,   x = testing_death_predict, color="Testing Predict Death" )) +
  scale_color_manual(values = c(
    "Death Prediction Based on Confirmed Cases" = "darkred",
    "Testing Predict Death" = "#E17876",
    "Hospital Predict Death" = "#2D6A4D",
    "ICU Predict Death" = "#59411A"
  ),name=NULL) +
  labs( title="California Confirmed Cases vs Deaths", 
        subtitle="Varous Regression Models (Last 30 Days)",
        y="Total California Confirmed Cases",
        x="Total California Covid Deaths" 
  )  


mean(death_model_post_may_df$confirm_death_offset)
mean(death_model_post_may_df$confirm_hospital_offset)

ggplot() + theme_light() + 
  theme( 
    panel.background = element_rect(fill = "lavenderblush"),
    legend.position = c(.8,.29), 
    legend.direction = "vertical") +
  geom_line(data = death_model_post_may_df, size=.5,aes(y = confirm_death_offset,   x = date,color='Days: Confirmed to Death')) +
  geom_line(data = death_model_post_may_df, size=.5,aes(y = confirm_hospital_offset,   x = date,color='Days: Confirmed to Hospitalization')) +
  scale_color_manual(values = c(
    "Days: Confirmed to Death" = "darkred",
    "Days: Confirmed to Hospitalization" = "#2D6A4D"
  ),name=NULL) +
  labs( title="Correlated Days between Confirmed Cases and Death/Hospitalization", 
        subtitle=NULL,
        y="Correlated Days with outcome",
        x=NULL 
  ) 


```

